export const types = {
	GET_ITEMS_PENDING: "GET_ITEMS_PENDING",
	GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
	GET_ITEMS_ERROR: "GET_ITEMS_ERROR",

	GET_ITEMS_DESC_PENDING: "GET_ITEMS_DESC_PENDING",
	GET_ITEMS_DESC_SUCCESS: "GET_ITEMS_DESC_SUCCESS",
	GET_ITEMS_DESC_ERROR: "GET_ITEMS_DESC_ERROR",

	ADD_ITEM: "ADD_ITEM",
	ADD_TASK: "ADD_TASK",
	SAVE_ITEM: "SAVE_ITEM",

	DELETE_TASK: "DELETE_TASK",

	SEARCH_TASK: "SEARCH_TASK",

	GET_TRELLO: "GET_TRELLO",
	CHANGE_TRELLO: "CHANGE_TRELLO"
}

export const globalTypes = {
	SUCCESS: "SUCCESS",
	PENDING: "PENDING",
	ERROR: "ERROR"
}
