export const authTypes = {
    LOGIN_PENDING: "LOGIN_PENDING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    CHANGE_IS_LOGIN: "CHANGE_IS_LOGIN",
    LOG_OUT: "LOG_OUT",

    REG_PENDING: "REG_PENDING",
    REG_ERROR: "REG_ERROR",
    REG_SUCCESS: "REG_SUCCESS"
}
